[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#B92B27"
backgroundColor = "#F7F3EE"
secondarybackgroundColor = "#F7F3EE"
textColor = "#262626"
font = "sans serif"

